<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151004145409 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD shortdescription VARCHAR(255) NOT NULL, ADD description VARCHAR(255) NOT NULL, DROP released, DROP runtime, DROP director, DROP writer, DROP plot, DROP language, DROP country, DROP awards, DROP actors, DROP type, DROP poster, DROP imdbvotes, CHANGE imdbrating rating DOUBLE PRECISION NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD released VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD runtime INT NOT NULL, ADD director VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD writer VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD plot VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD language VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD country VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD awards VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD actors VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD poster VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD imdbvotes VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, DROP shortdescription, DROP description, CHANGE rating imdbrating DOUBLE PRECISION NOT NULL");
	}
}