<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150918070208 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD poster VARCHAR(255) NOT NULL, ADD imdbvotes VARCHAR(255) NOT NULL, CHANGE released released VARCHAR(255) NOT NULL, CHANGE imgurl actors VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD imgurl VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, DROP actors, DROP poster, DROP imdbvotes, CHANGE released released DATETIME NOT NULL");
	}
}