<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151014205829 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD link VARCHAR(255) NOT NULL, DROP imdbid, DROP shortdescription, CHANGE description description LONGTEXT NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE maxs_randommovie_domain_model_movie ADD shortdescription VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE description description VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE link imdbid VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci");
	}
}