<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150906162246 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE maxs_randommovie_domain_model_movie (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, year INT NOT NULL, released DATETIME NOT NULL, runtime INT NOT NULL, genre VARCHAR(255) NOT NULL, director VARCHAR(255) NOT NULL, writer VARCHAR(255) NOT NULL, plot VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, awards VARCHAR(255) NOT NULL, imgurl VARCHAR(255) NOT NULL, metascore INT NOT NULL, imdbrating DOUBLE PRECISION NOT NULL, imdbid VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE maxs_randommovie_domain_model_movie");
	}
}